# Generated by Django 2.0.2 on 2018-02-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user_data',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
