# Generated by Django 2.0.2 on 2018-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmatch', '0002_auto_20180225_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
    ]
